# Generated by Django 4.2.2 on 2023-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
